"""Alinear modelos con esquema actualizado

Revision ID: b2941d822221
Revises: 6cb064190c6a
Create Date: 2025-05-14 22:11:44.768551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2941d822221'
down_revision = '6cb064190c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Personas', ['ID_Persona'], ['ID_Persona'])
        batch_op.create_foreign_key(None, 'Cuotas', ['ID_Cuota'], ['ID_Cuota'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
