"""Alinea modelos con esquema SQL

Revision ID: c05625227b27
Revises: f22cf293515a
Create Date: 2025-05-06 21:52:30.250613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c05625227b27'
down_revision = 'f22cf293515a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Cuotas', schema=None) as batch_op:
        batch_op.alter_column('Monto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=9, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Egresos', schema=None) as batch_op:
        batch_op.alter_column('Monto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=9, scale=2),
               existing_nullable=False)
        batch_op.alter_column('Descripcion',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('Ingresos', schema=None) as batch_op:
        batch_op.alter_column('Monto',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=9, scale=2),
               existing_nullable=False)
        batch_op.alter_column('Observaciones',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.alter_column('Monto_Pagado',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=9, scale=2),
               existing_nullable=False)
        batch_op.drop_constraint('FK__Pagos__ID_Cuota__5FB337D6', type_='foreignkey')
        batch_op.drop_constraint('FK_Pago_Persona_Cuota', type_='foreignkey')
        batch_op.drop_constraint('FK__Pagos__ID_Person__5EBF139D', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.create_foreign_key('FK__Pagos__ID_Person__5EBF139D', 'Personas', ['ID_Persona'], ['ID_Persona'])
        batch_op.create_foreign_key('FK_Pago_Persona_Cuota', 'Persona_Cuota', ['ID_Persona', 'ID_Cuota'], ['ID_Persona', 'ID_Cuota'])
        batch_op.create_foreign_key('FK__Pagos__ID_Cuota__5FB337D6', 'Cuotas', ['ID_Cuota'], ['ID_Cuota'])
        batch_op.alter_column('Monto_Pagado',
               existing_type=sa.Numeric(precision=9, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Ingresos', schema=None) as batch_op:
        batch_op.alter_column('Observaciones',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('Monto',
               existing_type=sa.Numeric(precision=9, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Egresos', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('Monto',
               existing_type=sa.Numeric(precision=9, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Cuotas', schema=None) as batch_op:
        batch_op.alter_column('Monto',
               existing_type=sa.Numeric(precision=9, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B6146E0BB3E')
    )
    # ### end Alembic commands ###
