"""Initial database schema

Revision ID: f22cf293515a
Revises: 
Create Date: 2025-05-06 21:32:39.924230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f22cf293515a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Persona_Cuota')
    op.drop_table('sysdiagrams')
    op.drop_table('Derecho_Cuota')
    with op.batch_alter_table('Egresos', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('Ingresos', schema=None) as batch_op:
        batch_op.alter_column('Observaciones',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('FK_Ingreso_Pago', type_='foreignkey')
        batch_op.drop_column('ID_Pago')

    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.drop_constraint('FK_Pago_Persona_Cuota', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pagos', schema=None) as batch_op:
        batch_op.create_foreign_key('FK_Pago_Persona_Cuota', 'Persona_Cuota', ['ID_Persona', 'ID_Cuota'], ['ID_Persona', 'ID_Cuota'])

    with op.batch_alter_table('Ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID_Pago', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('FK_Ingreso_Pago', 'Pagos', ['ID_Pago'], ['ID_Pago'])
        batch_op.alter_column('Observaciones',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('Egresos', schema=None) as batch_op:
        batch_op.alter_column('Descripcion',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    op.create_table('Derecho_Cuota',
    sa.Column('ID_Derecho', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ID_Cuota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ID_Cuota'], ['Cuotas.ID_Cuota'], name='FK_DC_Cuota'),
    sa.ForeignKeyConstraint(['ID_Derecho'], ['Derechos.ID_Derecho'], name='FK_DC_Derecho'),
    sa.PrimaryKeyConstraint('ID_Derecho', 'ID_Cuota', name='PK_Derecho_Cuota')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B6146E0BB3E')
    )
    op.create_table('Persona_Cuota',
    sa.Column('ID_Persona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ID_Cuota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Fecha_Asig', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Estado', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), server_default=sa.text("('Pendiente')"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ID_Cuota'], ['Cuotas.ID_Cuota'], name='FK_PC_Cuota'),
    sa.ForeignKeyConstraint(['ID_Persona'], ['Personas.ID_Persona'], name='FK_PC_Persona'),
    sa.PrimaryKeyConstraint('ID_Persona', 'ID_Cuota', name='PK_Persona_Cuota')
    )
    # ### end Alembic commands ###
